import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import InstrumentForm from '../components/InstrumentForm';

export default function Home() {
	
	const router = useRouter();

	const onSubmit = (studentNumber: string, instrumentNumber: string) => {
		console.log(studentNumber, instrumentNumber)
	}

	return (
		<>
			<Head>
				<title>Music App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Instrument Form */}
			<InstrumentForm onSubmit={onSubmit} defaultInputs={{ serialNumber: router.query.serialNumber as string }}/>
		</>
	)
}

// w*-Ft$E35NTJq+2