import Head from 'next/head'
import { Inter } from 'next/font/google'
import InstrumentForm from '../components/InstrumentForm';

const inter = Inter({
	subsets: ['latin'],
	weight: ["100", "300", "400"]
})

export default function Home() {
  return (
    <>
		<Head>
			<title>Music App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		{/* Instrument Form */}
		<InstrumentForm onSubmit={() => {}}/>
    </>
  )
}

// w*-Ft$E35NTJq+2